#!/usr/bin/env node
// Stitches the shared blocks into each prompt.
//   node build.mjs
// Edit src/ only. prompts/ is generated.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const SRC = join(HERE, 'src')
const OUT = join(HERE, 'prompts')
mkdirSync(OUT, { recursive: true })

const block = (name) => readFileSync(join(SRC, `_${name}.md`), 'utf8').trim()
const blocks = { RULES: block('rules'), LEDGER: block('ledger'), CLOSE: block('close') }

const words = (s) => (s.match(/\S+/g) || []).length
const rows = []

for (const f of readdirSync(SRC).filter((f) => /^F\d-.*\.md$/.test(f)).sort()) {
  let body = readFileSync(join(SRC, f), 'utf8')
  const bodyWords = words(body.replace(/\{\{\w+\}\}/g, ''))
  for (const [k, v] of Object.entries(blocks)) body = body.replaceAll(`{{${k}}}`, v)
  const left = body.match(/\{\{\w+\}\}/g)
  if (left) throw new Error(`${f}: unresolved ${left.join(', ')}`)
  if (body.includes('—')) throw new Error(`${f}: contains an em-dash`)
  const header = `<!-- Generated by tools/build.mjs from src/${f}. Edit src/, not this file. -->\n\n`
  writeFileSync(join(OUT, f), header + body.trim() + '\n')
  rows.push({ prompt: f.replace(/\.md$/, ''), body: bodyWords, total: words(body), chars: body.length })
}

console.log('prompt'.padEnd(24), 'workflow words', 'total words', 'characters')
for (const r of rows) console.log(r.prompt.padEnd(24), String(r.body).padStart(14), String(r.total).padStart(11), String(r.chars).padStart(10))
